### ISSUE TITLE
how to add more products? some add to cart buttons?

### ISSUE THREAD

**Issue by mafioznick** [CodyHouse/add-to-cart-interaction#1]
How to add more buttons?
I need some products to add to cart function (i need without price calculation, just add to cart and see all them in cart, quantity will be 1)

**Comment by mafioznick** [comment]
any help?

**Comment by sebastiano-guerriero** [comment]
I'm afraid it's not possible for us to help you integrate our resources in your code, or develop new features on the fly based on users requests.
