### ISSUE TITLE
Save Cart to localstorage

### ISSUE THREAD

**Issue by JohnMaze** [CodyHouse/add-to-cart-interaction#3]
Hey CodyHouse,

Is there any way the jQuery can be changed to store the cart to the browser local storage so the items don't get removed from the cart when the page is refreshed?

Thanks,

John

**Comment by claudia-romano** [comment]
Hi John, we do not plan on including a local storage implementation but the addProduct and removeProduct functions are the ones you would need to update to save your products to the local storage.

You can take a look at this article if you want to learn more about the API:
https://codyhouse.co/blog/post/store-theme-color-preferences-with-localstorage
